### ISSUE TITLE
Reproduce SRD v1 for 3x2pt

### ISSUE THREAD

**Issue by slosar** [LSSTDESC/augur#10]
Reproducing SRD v1 ~exactly would be a good first  test of augur.
It would take:
 *  implement redshift-dependent scale cut 
 * implement SRD v1 N(z) functional form 
 * spend some time creating the correct yaml config
 * write FOM calculator
 * DEBUG!

**Comment by fjaviersanchez** [comment]
![image](https://user-images.githubusercontent.com/13971732/115480031-49b8f780-a20f-11eb-9181-4d1834c1a30b.png)
![image](https://user-images.githubusercontent.com/13971732/115480041-50e00580-a20f-11eb-9a5e-285a427d06ad.png)
Using the config files in the branch `issues/11` I get the results above

**Comment by slosar** [comment]
Yey! This looks pretty good!
