### ISSUE TITLE
Fix astropy warnings

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/augur#27]
We have some warnings from Astropy when running the example from the SRD:

`WARNING: AstropyDeprecationWarning: output_fishery1/latex_table.tex already exists. Automatically overwriting ASCII files is deprecated. Use the argument 'overwrite=True' in the future. [astropy.io.ascii.ui]
WARNING:astropy:AstropyDeprecationWarning: output_fishery1/latex_table.tex already exists. Automatically overwriting ASCII files is deprecated. Use the argument 'overwrite=True' in the future.
`
We should fixe them to get the desired behavior from that library in the future.

**Comment by fjaviersanchez** [comment]
This is not an issue in the new versions.
