### ISSUE TITLE
Deal with phatom divide somehow

### ISSUE THREAD

**Issue by slosar** [LSSTDESC/augur#3]
At the moment if you try to run Fisher with w as a parameter it complains about going over phantom divide, because Fisher needs to do steps around fiducial w=-1. F

**Comment by slosar** [comment]
See https://lsstc.slack.com/archives/C46JK16F6/p1589221881259900

**Comment by fjaviersanchez** [comment]
This is solved with the `extra_parameters` parameter in the `Cosmology` objects in the current master but not yet available in the latest tagged version. For now, the way I dealt with this was changing the transfer function to `eisenstein_hu`. Once the new version is tagged, and in conda, I'll just modify the config files.

**Comment by slosar** [comment]
Ok, great, thanks.
