### ISSUE TITLE
Broken with firecrown 1.7.4

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/augur#43]
Now `TwoPoint` from `likelihood.gauss_family.statistic` is deprecated and there's an updated class that needs to be used in order for the code to run.

**Comment by marcpaterno** [comment]
The head of `master` in firecrown contains a simplification (compression) of the too-deep directory structure. For backwards compatibility, there are stubs in place that (1) emit deprecation warnings and (2) include the newer file.

**Comment by fjaviersanchez** [comment]
Thanks @marcpaterno. I saw that there was a change in the `TwoPoint` class that removes `ell_or_theta_`, so I still need to update that (it's probably my bad, using some tricky-sneaky way to get the bin centers)

**Comment by fjaviersanchez** [comment]
Closed by #44
