### ISSUE TITLE
Implment corner plot and basic tables

### ISSUE THREAD

**Issue by slosar** [LSSTDESC/augur#5]
Analysis functionality is now empty. At the minimum it should implement a corner plot functionality and a list of marginalized constraints.

**Comment by fjaviersanchez** [comment]
A preliminary result: 
[triangle_plot.pdf](https://github.com/LSSTDESC/augur/files/6535822/triangle_plot.pdf)
[w0--wa.pdf](https://github.com/LSSTDESC/augur/files/6535823/w0--wa.pdf)
[omega_c--sigma8.pdf](https://github.com/LSSTDESC/augur/files/6535824/omega_c--sigma8.pdf)

**Comment by slosar** [comment]
Can we generate these algorithmically? I.e. say if I make two sets of forecasts using fircrown, can I make these using a notebook or something?

**Comment by fjaviersanchez** [comment]
yeah, the functions are already implemented in a branch [here](https://github.com/LSSTDESC/augur/tree/issues/5). I just didn't open a PR yet because I wanted to clean up the formatting a bit more.

**Comment by fjaviersanchez** [comment]
I added a section where you plot everything against everything, and another section in the config where pass a list of pairs of quantities that you'd like to plot.

**Comment by elisachisari** [comment]
Shall we close this?

**Comment by fjaviersanchez** [comment]
Closed by #14
