### ISSUE TITLE
Bug in redshift distribution especially affecting the first source bin

### ISSUE THREAD

**Issue by heatherprince** [LSSTDESC/augur#51]
Source bin 1 has a nonzero value at z=0 which does not match the SRD redshift distribution implemented by Niko and Paul. It led to large discrepancies for power spectrum, especially for combinations with the first bin. I think this is caused by how the Gaussian filtering is implemented in Augur.

**Comment by heatherprince** [comment]
The default mode for [scipy.gaussian_filter](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.gaussian_filter.html) is reflect, which is going to do weird things at the edges of the array. I think we want constant with zeros.

**Comment by arthurmloureiro** [comment]
Benchmarked against @paulrogozenski notebooks in the forecasting repository. 

There is a normalization factor that causes them to be a bit different but this is not relevant...
<img width="447" alt="Screenshot 2024-07-04 at 17 21 33" src="https://github.com/LSSTDESC/augur/assets/6471279/2844697f-f53f-4941-a533-cfe232708c59">

old augur:
<img width="329" alt="Screenshot 2024-07-04 at 17 22 11" src="https://github.com/LSSTDESC/augur/assets/6471279/db51f1b3-602f-4c47-8593-8d36a3b4c50b">
